#!/bin/bash

set -o errexit -o nounset -o pipefail

destination="$1"
timestamp="$2"

rm -rf "$destination"
mkdir "$destination"

mkdir "$destination/$timestamp"
cp -a /srv/mail "$destination/$timestamp/mail"
tar -cC "$destination" "$timestamp" | zstd -9 --long | age -r $(cat backup-public-key.txt) -o "$destination/$timestamp.tar.zst.age"
