#!/bin/bash

set -o errexit -o nounset -o pipefail

timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
rm -rf remote-backup
mkdir remote-backup

mkdir remote-backup/$timestamp
cp -a /home/ remote-backup/$timestamp/home
tar -cC remote-backup $timestamp | zstd -9 | age -r $(cat backup-public-key.txt) -o remote-backup/$timestamp.tar.zst.age

source cloud-archive.sh
swift upload --skip-container-put --segment-size 5368709122 -H "X-Delete-After: 5184000" \
    --object-name $timestamp.tar.zst.age backup remote-backup/$timestamp.tar.zst.age

rm -rf remote-backup
