dovecot_config_version = 2.4.4
dovecot_storage_version = 2.4.4

protocols = imap lmtp
mail_utf8_extensions = yes

mail_driver = maildir
mailbox_list_utf8 = yes

first_valid_uid = 10000
first_valid_gid = 10000

namespace inbox {
  inbox = yes

  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }

  mailbox Spam {
    auto = subscribe
    special_use = \Junk
  }

  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }

  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
}

auth_default_domain = grapheneos.org

passdb passwd-file {
  passwd_file_path = /etc/dovecot/shadow
  passdb_use_worker = yes
}

userdb passwd-file {
  passwd_file_path = /etc/dovecot/passwd
  fields {
    home = /srv/mail/%{user}
  }
}

service imap-login {
  inet_listener imap {
    port = 0
  }
}

service auth {
  group = dovecot-auth

  unix_listener /var/spool/postfix/dovecot/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}

service auth-worker {
  user = $SET:default_internal_user
  group = dovecot-auth
}

service lmtp {
  unix_listener /var/spool/postfix/dovecot/lmtp {
    mode = 0660
    user = postfix
    group = postfix
  }
}

protocol lmtp {
  mail_plugins {
    sieve = yes
  }
}

sieve_script default {
  path = /etc/dovecot/sieve
  active_path = /etc/dovecot/sieve/default.sieve
}

ssl = required
ssl_min_protocol = TLSv1.3

ssl_server {
  cert_file = /etc/letsencrypt/live/mail.grapheneos.org/fullchain.pem
  key_file = /etc/letsencrypt/live/mail.grapheneos.org/privkey.pem
  prefer_ciphers = server
}
