dovecot_config_version = 2.4.3
dovecot_storage_version = 2.4.3

protocols = imap lmtp
mail_utf8_extensions = yes

mail_driver = maildir
mailbox_list_utf8 = yes

first_valid_uid = 1000

@mailbox_defaults = english

auth_username_format = %{user|username}

passdb pam {
}

userdb passwd {
}

service imap-login {
  inet_listener imap {
    port = 0
  }
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0660
    user = postfix
    group = postfix
  }
}

ssl = required
ssl_server_prefer_ciphers = server
ssl_min_protocol = TLSv1.3

ssl_server {
  cert_file = /etc/letsencrypt/live/mail.grapheneos.org/fullchain.pem
  key_file = /etc/letsencrypt/live/mail.grapheneos.org/privkey.pem
}
