SPF_SOFTFAIL_WITHOUT_DMARC_POLICY_ALLOW {
  expression = "R_SPF_SOFTFAIL & !DMARC_POLICY_ALLOW";
  score = 4.0;
}

NOT_DMARC_POLICY_ALLOW {
  expression = "!DMARC_POLICY_ALLOW";
  group = "dmarc";
  score = 1.0;
}

MIME_ARCHIVE_IN_ARCHIVE_WITH_BUGREPORT_ZIP {
  expression = "MIME_ARCHIVE_IN_ARCHIVE & BUGREPORT_ZIP";
  policy = "leave";
  score = -5.0;
}

LOGS_URL_NUMERIC_IP {
  expression = "LOGS & -URL_NUMERIC_IP";
  score = -9.0;
}

LOGS_SUSPICIOUS_URL_IN_SUSPICIOUS_MESSAGE {
  expression = "LOGS & SUSPICIOUS_URL_IN_SUSPICIOUS_MESSAGE";
}

FROM_NEQ_ENVFROM_VERP_SRS {
  expression = "FROM_NEQ_ENVFROM & (ENVFROM_PRVS | ENVFROM_VERP)";
}

SPAM_SUBJECT_AND_BODY_TEXT {
  expression = "SPAM_SUBJECT_TEXT & SPAM_BODY_TEXT";
  score = 9.0;
}

EXCESS_RECEIVED_SPAMHAUS_SBL {
  expression = "-RBL_SPAMHAUS_SBL & RECEIVED_SPAMHAUS_SBL";
  policy = "remove_weight";
}

EXCESS_RECEIVED_SPAMHAUS_CSS {
  expression = "-RBL_SPAMHAUS_CSS & RECEIVED_SPAMHAUS_CSS";
  policy = "remove_weight";
}

EXCESS_RECEIVED_SPAMHAUS_XBL {
  expression = "-RBL_SPAMHAUS_XBL & RECEIVED_SPAMHAUS_XBL";
  policy = "remove_weight";
}

EXCESS_RECEIVED_SPAMHAUS_PBL {
  expression = "-RBL_SPAMHAUS_PBL & RECEIVED_SPAMHAUS_PBL";
  policy = "remove_weight";
}

EXCESS_RECEIVED_SPAMHAUS_DROP {
  expression = "-RBL_SPAMHAUS_DROP & RECEIVED_SPAMHAUS_DROP";
  policy = "remove_weight";
}

EXCESS_RECEIVED_ABUSIX_SPAM {
  expression = "-RBL_ABUSIX_SPAM & RECEIVED_ABUSIX_SPAM";
  policy = "remove_weight";
}

EXCESS_RECEIVED_ABUSIX_SPAM_HEURISTIC {
  expression = "-RBL_ABUSIX_SPAM_HEURISTIC & RECEIVED_ABUSIX_SPAM_HEURISTIC";
  policy = "remove_weight";
}

EXCESS_RECEIVED_ABUSIX_SPAM_MANUAL {
  expression = "-RBL_ABUSIX_SPAM_MANUAL & RECEIVED_ABUSIX_SPAM_MANUAL";
  policy = "remove_weight";
}

EXCESS_RECEIVED_ABUSIX_EXPLOIT {
  expression = "-RBL_ABUSIX_EXPLOIT & RECEIVED_ABUSIX_EXPLOIT";
  policy = "remove_weight";
}

EXCESS_RECEIVED_SPAMCOP {
  expression = "-RBL_SPAMCOP & RECEIVED_SPAMCOP";
  policy = "remove_weight";
}

EXCESS_RECEIVED_BARRACUDA {
  expression = "-RBL_BARRACUDA & RECEIVED_BARRACUDA";
  policy = "remove_weight";
}

EXCESS_RECEIVED_TRUNCATE {
  expression = "-RBL_TRUNCATE & RECEIVED_TRUNCATE";
  policy = "remove_weight";
}

EXCESS_RECEIVED_SEM {
  expression = "-RBL_SEM & RECEIVED_SEM";
  policy = "remove_weight";
}

EXCESS_RECEIVED_SEM_IPV6 {
  expression = "-RBL_SEM_IPV6 & RECEIVED_SEM_IPV6";
  policy = "remove_weight";
}

EXCESS_RECEIVED_PSBL {
  expression = "-RBL_PSBL & RECEIVED_PSBL";
  policy = "remove_weight";
}

EXCESS_RECEIVED_FABEL {
  expression = "-RBL_FABEL & RECEIVED_FABEL";
  policy = "remove_weight";
}

EXCESS_RECEIVED_VIRUSFREE_BAD {
  expression = "-RBL_VIRUSFREE_BAD & RECEIVED_VIRUSFREE_BAD";
  policy = "remove_weight";
}

EXCESS_RECEIVED_VIRUSFREE_BOTNET {
  expression = "-RBL_VIRUSFREE_BOTNET & RECEIVED_VIRUSFREE_BOTNET";
  policy = "remove_weight";
}

EXCESS_RECEIVED_BLOCKLISTDE {
  expression = "-RBL_BLOCKLISTDE & RECEIVED_BLOCKLISTDE";
  policy = "remove_weight";
}

EXCESS_RECEIVED_SINGULAR {
  expression = "-RBL_SINGULAR & RECEIVED_SINGULAR";
  policy = "remove_weight";
}

EXCESS_RECEIVED_ANONMAILSDE {
  expression = "-RBL_ANONMAILSDE & RECEIVED_ANONMAILSDE";
  policy = "remove_weight";
}

EXCESS_RECEIVED_EFNET {
  expression = "-RBL_EFNET & RECEIVED_EFNET";
  policy = "remove_weight";
}

RBL_SPAMHAUS_ZEN {
  expression = "RBL_SPAMHAUS_SBL | RBL_SPAMHAUS_CSS | RBL_SPAMHAUS_XBL | RBL_SPAMHAUS_PBL | RBL_SPAMHAUS_DROP";
  policy = "leave";
  score = 7.0;
}
RECEIVED_SPAMHAUS_ZEN {
  expression = "RECEIVED_SPAMHAUS_SBL | RECEIVED_SPAMHAUS_CSS | RECEIVED_SPAMHAUS_XBL | RECEIVED_SPAMHAUS_DROP";
  policy = "leave";
  score = 3.5;
}
EXCESS_SPAMHAUS_ZEN {
  expression = "-RBL_SPAMHAUS_ZEN & RECEIVED_SPAMHAUS_ZEN";
  policy = "remove_weight";
}
