SPF_SOFTFAIL_WITHOUT_DMARC_POLICY_ALLOW {
  expression = "R_SPF_SOFTFAIL & !DMARC_POLICY_ALLOW";
  score = 14.0;
}

NOT_DMARC_POLICY_ALLOW {
  expression = "!DMARC_POLICY_ALLOW";
  group = "dmarc";
  score = 1.0;
}

MIME_ARCHIVE_IN_ARCHIVE_WITH_BUGREPORT_ZIP {
  expression = "-MIME_ARCHIVE_IN_ARCHIVE & BUGREPORT_ZIP";
  score = -5.0
}

FROM_NEQ_ENVFROM_VERP_SRS {
  expression = "FROM_NEQ_ENVFROM & (ENVFROM_PRVS | ENVFROM_VERP)";
}
