rules {
  LOCAL_FORGED_SENDER {
    action = "reject";
    expression = "(LOCAL_OUTBOUND | INTERNAL_MAIL) & FORGED_SENDER";
    message = "Sender is forged (different From: header and smtp MAIL FROM: addresses)";
  }

  LOCAL_FORGED_RECIPIENTS {
    action = "reject";
    expression = "(LOCAL_OUTBOUND | INTERNAL_MAIL) & FORGED_RECIPIENTS";
    message = "Recipients are not the same as RCPT TO: mail command";
  }

  SPF_FAIL_WITHOUT_DMARC_POLICY_ALLOW {
    action = "reject";
    expression = "R_SPF_FAIL & !DMARC_POLICY_ALLOW";
    message = "SPF hardfail";
  }

  SPF_DNSFAIL_WITHOUT_DMARC_POLICY_ALLOW {
    action = "soft reject";
    expression = "R_SPF_DNSFAIL & !DMARC_POLICY_ALLOW";
    message = "SPF temperror";
  }

  SPF_PERMFAIL_WITHOUT_DMARC_POLICY_ALLOW {
    action = "reject";
    expression = "R_SPF_PERMFAIL & !DMARC_POLICY_ALLOW";
    message = "SPF permerror";
  }

  DMARC_UPGRADE {
    action = "quarantine";
    expression = "DMARC_UPGRADE & !DMARC_POLICY_ALLOW";
    honor_action = ["reject", "soft reject"];
  }
}
