rules {
  REJECT_SPF_FAIL {
    action = "reject";
    expression = "R_SPF_FAIL";
    message = "SPF hardfail";
  }

  REJECT_SPF_DNSFAIL {
    action = "soft reject";
    expression = "R_SPF_DNSFAIL";
    message = "SPF temperror";
  }

  REJECT_SPF_PERMFAIL {
    action = "reject";
    expression = "R_SPF_PERMFAIL";
    message = "SPF permerror";
  }
}
