rules {
  REJECT_LOCAL_FORGED_SENDER {
    action = "reject";
    expression = "(LOCAL_OUTBOUND | INTERNAL_MAIL) & FORGED_SENDER";
    message = "Sender is forged (different From: header and smtp MAIL FROM: addresses)";
  }

  REJECT_LOCAL_FORGED_RECIPIENTS {
    action = "reject";
    expression = "(LOCAL_OUTBOUND | INTERNAL_MAIL) & FORGED_RECIPIENTS";
    message = "Recipients are not the same as RCPT TO: mail command";
  }

  REJECT_SPF_FAIL {
    action = "reject";
    expression = "R_SPF_FAIL";
    message = "SPF hardfail";
  }

  REJECT_SPF_DNSFAIL {
    action = "soft reject";
    expression = "R_SPF_DNSFAIL";
    message = "SPF temperror";
  }

  REJECT_SPF_PERMFAIL {
    action = "reject";
    expression = "R_SPF_PERMFAIL";
    message = "SPF permerror";
  }
}
