symbols {
  "DMARC_BAD_POLICY" {
    weight = 1.0;
  }

  "DMARC_NA" {
    weight = 1.0;
  }

  "DMARC_POLICY_SOFTFAIL" {
    weight = 1.0;
  }

  "ARC_ALLOW" {
    weight = 0.0;
  }

  "ARC_ALLOW_TRUSTED" {
    weight = 0.0;
  }

  "RDNS_NONE" {
    weight = 5.0;
  }

  "FROM_NEQ_ENVFROM" {
    weight = 0.3;
  }

  "FORGED_SENDER" {
    weight = 0.0;
  }

  "RCPT_COUNT_TWELVE" {
    weight = 0.5;
  }

  "RCPT_COUNT_GT_50" {
    weight = 2.0;
  }

  "R_NO_SPACE_IN_FROM" {
    weight = 3.0;
  }
}
