symbols {
  # covered via broader NOT_DMARC_POLICY_ALLOW instead
  "DMARC_POLICY_SOFTFAIL" {
    weight = 0.0;
  }

  "ARC_ALLOW" {
    weight = 0.0;
  }

  "ARC_ALLOW_TRUSTED" {
    weight = 0.0;
  }

  "MISSING_MID" {
    weight = 6.0;
  }

  "R_NO_SPACE_IN_FROM" {
    weight = 6.0;
  }

  "FROM_NEQ_ENVFROM" {
    weight = 0.3;
  }

  "FORGED_SENDER" {
    weight = 0.0;
  }

  "RCPT_COUNT_TWELVE" {
    weight = 0.5;
  }

  "RCPT_COUNT_GT_50" {
    weight = 2.0;
  }

  # false positives for emails with Bitcoin addresses
  "LEAKED_PASSWORD_SCAM" {
    weight = 0.0;
  }
}
