symbols {
  "HFILTER_MID_NORESOLVE_MX" {
    description = "MX found in Message-id host and no resolve";
  }
  "HFILTER_MID_NORES_A_OR_MX" {
    description = "Message-id host no resolve to A or MX";
  }
  "HFILTER_MID_NOT_FQDN" {
    description = "Message-id host not FQDN";
  }
}
