symbols {
  "HFILTER_MID_NORESOLVE_MX" {
    description = "MX found in Message-id host and no resolve";
  }
  "HFILTER_MID_NORES_A_OR_MX" {
    description = "Message-id host no resolve to A or MX";
  }
  "HFILTER_MID_NOT_FQDN" {
    weight = 0.5;
    description = "Message-id host not FQDN";
  }

  # handled by MX_NONE
  "HFILTER_FROMHOST_NORES_A_OR_MX" {
    weight = 0.0;
  }

  # handled by MX_BROKEN
  "HFILTER_FROMHOST_NORESOLVE_MX" {
    weight = 0.0;
  }
}
