BLOCKLIST_ESLD_ENVFROM {
  type = "from";
  filter = "email:domain:tld";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_esld.map";
  action = "reject";
}

BLOCKLIST_ESLD_FROM {
  type = "header";
  header = "From";
  filter = "email:domain:tld";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_esld.map";
  action = "reject";
}

BLOCKLIST_ESLD_ENVRCPT {
  type = "rcpt";
  filter = "email:domain:tld";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_esld.map";
  action = "reject";
}

BLOCKLIST_ESLD_TO {
  type = "header";
  header = "To";
  filter = "email:domain:tld";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_esld.map";
  action = "reject";
}

BLOCKLIST_ESLD_CC {
  type = "header";
  header = "Cc";
  filter = "email:domain:tld";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_esld.map";
  action = "reject";
}

BLOCKLIST_ESLD_REPLYTO {
  type = "header";
  header = "Reply-To";
  filter = "email:domain:tld";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_esld.map";
  action = "reject";
}

BLOCKLIST_ESLD_MDN {
  type = "header";
  header = "Disposition-Notification-To";
  filter = "email:domain:tld";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_esld.map";
  action = "reject";
}

BLOCKLIST_ADDR_ENVFROM {
  type = "from";
  filter = "email:addr";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_addr.map";
  action = "reject";
}

BLOCKLIST_ADDR_FROM {
  type = "header";
  header = "From";
  filter = "email:addr";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_addr.map";
  action = "reject";
}

BLOCKLIST_ADDR_ENVRCPT {
  type = "rcpt";
  filter = "email:addr";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_addr.map";
  action = "reject";
}

BLOCKLIST_ADDR_TO {
  type = "header";
  header = "To";
  filter = "email:addr";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_addr.map";
  action = "reject";
}

BLOCKLIST_ADDR_CC {
  type = "header";
  header = "Cc";
  filter = "email:addr";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_addr.map";
  action = "reject";
}

BLOCKLIST_ADDR_REPLYTO {
  type = "header";
  header = "Reply-To";
  filter = "email:addr";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_addr.map";
  action = "reject";
}

BLOCKLIST_ADDR_MDN {
  type = "header";
  header = "Disposition-Notification-To";
  filter = "email:addr";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_addr.map";
  action = "reject";
}

BLOCKLIST_SUBJECT_TEXT {
  type = "header";
  header = "Subject";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_text.map";
  regexp = true;
  action = "reject";
}

SPAM_SUBJECT_TEXT {
  type = "header";
  header = "Subject";
  map = "$LOCAL_CONFDIR/local.d/maps.d/spam_text.map";
  regexp = true;
  score = 10.5;
}

BLOCKLIST_BODY_TEXT {
  type = "content";
  filter = "text";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_text.map";
  regexp = true;
  action = "reject";
}

SPAM_BODY_TEXT {
  type = "content";
  filter = "text";
  map = "$LOCAL_CONFDIR/local.d/maps.d/spam_text.map";
  regexp = true;
  score = 10.5;
}

BLOCKLIST_IP {
  type = "ip";
  map = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_ip.map";
  action = "reject";
}

TOR_EXIT {
  type = "ip";
  map = "$LOCAL_CONFDIR/local.d/maps.d/tor_exit.map";
  action = "reject";
}

DMARC_UPGRADE {
  require_symbols = "!DMARC_POLICY_ALLOW";
  type = "header";
  header = "From";
  filter = "email:domain:tld";
  map = "$LOCAL_CONFDIR/local.d/maps.d/dmarc_upgrade.map";
  action = "quarantine";
  message = null;
}
