enabled = true;

connect_timeout = 4.0;
read_timeout = 10.0;

verify_greeting = true;
send_quit = true;

expire_dns = 0;
expire_novalid = 600;
expire_timeout = 300;

reject_null_mx = true;

probe_ipv6 = true;

exclude_domains = [
  "$LOCAL_CONFDIR/local.d/maps.d/mx_check_exclude_domains.map",
  "https://maps.rspamd.com/rspamd/dmarc_whitelist_new.inc",
  "https://maps.rspamd.com/rspamd/spf_dkim_whitelist.inc",
  "https://maps.rspamd.com/rspamd/maillist.inc",
  "https://maps.rspamd.com/freemail/free.txt.zst",
  "https://maps.rspamd.com/freemail/disposable.txt.zst",
];
exclude_mxs = "$LOCAL_CONFDIR/local.d/maps.d/mx_check_exclude_mxs.map";

bad_mxs = "$LOCAL_CONFDIR/local.d/maps.d/mx_check_bad_mxs.map";
bad_ips = "$LOCAL_CONFDIR/local.d/maps.d/blocklist_ip.map";
