enabled = true;

read_timeout = 10.0;

verify_greeting = true;
send_quit = true;

expire_dns = 0;

reject_null_mx = true;

probe_ipv6 = true;

exclude_domains = [
  "${CONFDIR}/local.d/maps.d/mx_check_exclude_domains.map",
  "https://maps.rspamd.com/rspamd/dmarc_whitelist_new.inc",
  "https://maps.rspamd.com/rspamd/spf_dkim_whitelist.inc",
  "https://maps.rspamd.com/rspamd/maillist.inc",
  "https://maps.rspamd.com/freemail/free.txt.zst",
  "https://maps.rspamd.com/freemail/disposable.txt.zst",
];

exclude_mxs = [
  "${CONFDIR}/local.d/maps.d/mx_check_exclude_mxs.map",
];
