symbols {
  "MX_WHITE" {
    weight = 0.0;
  }
  "MIME_FROM_MX_WHITE" {
    weight = 0.0;
  }
  "REPLYTO_MX_WHITE" {
    weight = 0.0;
  }

  "MX_GOOD" {
    weight = 0.0;
  }
  "MIME_FROM_MX_GOOD" {
    weight = 0.0;
  }
  "REPLYTO_MX_GOOD" {
    weight = 0.0;
  }

  "MX_A_GOOD" {
    weight = 0.1;
  }
  "MIME_FROM_MX_A_GOOD" {
    weight = 0.1;
  }
  "REPLYTO_MX_A_GOOD" {
    weight = 0.1;
  }

  "MX_ERROR" {
    weight = 0.1;
  }
  "MIME_FROM_MX_ERROR" {
    weight = 0.1;
  }
  "REPLYTO_MX_ERROR" {
    weight = 0.1;
  }

  "MX_A_ERROR" {
    weight = 0.2;
  }
  "MIME_FROM_MX_A_ERROR" {
    weight = 0.2;
  }
  "REPLYTO_MX_A_ERROR" {
    weight = 0.2;
  }

  "MX_TIMEOUT_READ" {
    weight = 0.2;
  }
  "MIME_FROM_MX_TIMEOUT_READ" {
    weight = 0.2;
  }
  "REPLYTO_MX_TIMEOUT_READ" {
    weight = 0.2;
  }

  "MX_A_TIMEOUT_READ" {
    weight = 0.3;
  }
  "MIME_FROM_MX_A_TIMEOUT_READ" {
    weight = 0.3;
  }
  "REPLYTO_MX_A_TIMEOUT_READ" {
    weight = 0.3;
  }
}
