symbols {
  "MX_WHITE" {
    weight = 0.0;
  }
  "MIME_FROM_MX_WHITE" {
    weight = 0.0;
  }
  "REPLYTO_MX_WHITE" {
    weight = 0.0;
  }

  "MX_GOOD" {
    weight = 0.0;
  }
  "MIME_FROM_MX_GOOD" {
    weight = 0.0;
  }
  "REPLYTO_MX_GOOD" {
    weight = 0.0;
  }

  "MX_A_GOOD" {
    weight = 0.1;
  }
  "MIME_FROM_MX_A_GOOD" {
    weight = 0.05;
  }
  "REPLYTO_MX_A_GOOD" {
    weight = 0.05;
  }

  "MX_ERROR" {
    weight = 0.1;
  }
  "MIME_FROM_MX_ERROR" {
    weight = 0.05;
  }
  "REPLYTO_MX_ERROR" {
    weight = 0.05;
  }

  "MX_A_ERROR" {
    weight = 0.2;
  }
  "MIME_FROM_MX_A_ERROR" {
    weight = 0.1;
  }
  "REPLYTO_MX_A_ERROR" {
    weight = 0.1;
  }

  "MX_TIMEOUT_READ" {
    weight = 0.2;
  }
  "MIME_FROM_MX_TIMEOUT_READ" {
    weight = 0.1;
  }
  "REPLYTO_MX_TIMEOUT_READ" {
    weight = 0.1;
  }

  "MX_A_TIMEOUT_READ" {
    weight = 0.3;
  }
  "MIME_FROM_MX_A_TIMEOUT_READ" {
    weight = 0.15;
  }
  "REPLYTO_MX_A_TIMEOUT_READ" {
    weight = 0.15;
  }

  "MX_NONE" {
    weight = 8.0;
  }
  "MIME_FROM_MX_NONE" {
    weight = 4.0;
  }
  "REPLYTO_MX_NONE" {
    weight = 4.0;
  }

  "MX_BROKEN" {
    weight = 8.0;
  }
  "MIME_FROM_MX_BROKEN" {
    weight = 4.0;
  }
  "REPLYTO_MX_BROKEN" {
    weight = 4.0;
  }

  "MX_LOCAL_ONLY" {
    weight = 8.0;
  }
  "MIME_FROM_LOCAL_ONLY" {
    weight = 4.0;
  }
  "REPLYTO_LOCAL_ONLY" {
    weight = 4.0;
  }

  "MX_BOGON_ONLY" {
    weight = 8.0;
  }
  "MIME_FROM_BOGON_ONLY" {
    weight = 4.0;
  }
  "REPLYTO_BOGON_ONLY" {
    weight = 4.0;
  }

  "MX_REFUSED" {
    weight = 6.0;
  }
  "MIME_FROM_MX_REFUSED" {
    weight = 3.0;
  }
  "REPLYTO_MX_REFUSED" {
    weight = 3.0;
  }

  "MX_A_REFUSED" {
    weight = 7.0;
  }
  "MIME_FROM_MX_A_REFUSED" {
    weight = 3.5;
  }
  "REPLYTO_MX_A_REFUSED" {
    weight = 3.5;
  }

  "MX_TIMEOUT_CONNECT" {
    weight = 6.0;
  }
  "MIME_FROM_MX_TIMEOUT_CONNECT" {
    weight = 3.0;
  }
  "REPLYTO_MX_TIMEOUT_CONNECT" {
    weight = 3.0;
  }

  "MX_A_TIMEOUT_CONNECT" {
    weight = 7.0;
  }
  "MIME_FROM_MX_A_TIMEOUT_CONNECT" {
    weight = 3.5;
  }
  "REPLYTO_MX_A_TIMEOUT_CONNECT" {
    weight = 3.5;
  }

  "MX_INVALID" {
    weight = 6.0;
  }
  "MIME_FROM_MX_INVALID" {
    weight = 3.0;
  }
  "REPLYTO_MX_INVALID" {
    weight = 3.0;
  }

  "MX_A_INVALID" {
    weight = 7.0;
  }
  "MIME_FROM_MX_A_INVALID" {
    weight = 3.5;
  }
  "REPLYTO_MX_A_INVALID" {
    weight = 3.5;
  }
}
