symbols {
  # covered via broader NOT_DMARC_POLICY_ALLOW instead
  "DMARC_POLICY_SOFTFAIL" {
    weight = 0.0;
  }

  "ARC_ALLOW" {
    weight = 0.0;
  }

  "ARC_ALLOW_TRUSTED" {
    weight = 0.0;
  }
}
