rbls {
  senderscore {
    enabled = true;
  }

  senderscore_reputation {
    enabled = true;
  }

  RSPAMD_EMAILBL {
    enabled = false;
  }

  MSBL_EBL {
    enabled = false;
  }

  SURBL_MULTI {
    exclude_checks = ["emails", "urls", "content_urls"];
  }

  SURBL_HASHBL {
    enabled = false;
  }

  URIBL_MULTI {
    exclude_checks = ["emails", "urls", "content_urls"];
  }

  RSPAMD_URIBL {
    exclude_checks = ["emails", "urls", "content_urls"];
  }

  DBL {
    exclude_checks = ["emails", "urls", "content_urls"];
  }

  SEM_URIBL_UNKNOWN {
    exclude_checks = ["emails", "urls", "content_urls"];
  }

  SEM_URIBL_FRESH15_UNKNOWN {
    exclude_checks = ["emails", "urls", "content_urls"];
  }

  spamcop {
    symbol = "SPAMCOP";
    rbl = "bl.spamcop.net";
    checks = ["from", "received"];
    symbols_prefixes = {
      received = "RECEIVED",
      from = "RBL",
    }
  }

  barracuda {
    symbol = "BARRACUDA";
    rbl = "b.barracudacentral.org";
    checks = ["from", "received"];
    symbols_prefixes = {
      received = "RECEIVED",
      from = "RBL",
    }
  }
}
