rbls {
  RSPAMD_EMAILBL {
    enabled = false;
  }

  MSBL_EBL {
    enabled = false;
  }

  SURBL_MULTI {
    exclude_checks = ["emails", "urls", "content_urls"];
  }

  SURBL_HASHBL {
    enabled = false;
  }

  URIBL_MULTI {
    exclude_checks = ["emails", "urls", "content_urls"];
  }

  RSPAMD_URIBL {
    exclude_checks = ["emails", "urls", "content_urls"];
  }

  DBL {
    exclude_checks = ["emails", "urls", "content_urls"];
  }

  SEM_URIBL_UNKNOWN {
    exclude_checks = ["emails", "urls", "content_urls"];
  }

  SEM_URIBL_FRESH15_UNKNOWN {
    exclude_checks = ["emails", "urls", "content_urls"];
  }
}
