symbols {
  # reduce weight to match RWL_MAILSPIKE_GOOD due to lack of fine-grained tiers
  "RBL_SENDERSCORE_REPUT_9" {
    weight = -0.1;
  }

  "RBL_ABUSIX" {
      weight = 0.0;
      description = "Unrecognised result from Abusix Combined Blocklist";
      groups = ["abusix"];
  }
  "RBL_ABUSIX_SPAM" {
      weight = 2.0;
      description = "From address is listed in Abusix Spam Blocklist";
      groups = ["abusix"];
  }
  "RBL_ABUSIX_EXPLOIT" {
      weight = 4.0;
      description = "From address is listed in Abusix Exploit Blocklist";
      groups = ["abusix"];
  }
  "RBL_ABUSIX_POLICY" {
      weight = 2.0;
      description = "From address is listed in Abusix Policy Blocklist";
      groups = ["abusix"];
  }
  "RECEIVED_ABUSIX_SPAM" {
      weight = 1.0;
      description = "Received address is listed in Abusix Spam Blocklist";
      groups = ["abusix"];
      one_shot = true;
  }
  "RECEIVED_ABUSIX_EXPLOIT" {
      weight = 1.0;
      description = "Received address is listed in Abusix Exploit Blocklist";
      groups = ["abusix"];
      one_shot = true;
  }
  "RECEIVED_ABUSIX_POLICY" {
      weight = 0.0;
      description = "Received address is listed in Abusix Policy Blocklist";
      groups = ["abusix"];
      one_shot = true;
  }

  "RBL_SPAMCOP" {
    weight = 2.0;
    description = "From address is listed in SpamCop Blocking List (SCBL)";
    groups = ["spamcop"];
  }
  "RECEIVED_SPAMCOP" {
    weight = 1.0;
    description = "Received address is listed in SpamCop Blocking List (SCBL)";
    groups = ["spamcop"];
    one_shot = true;
  }

  "RBL_BARRACUDA" {
    weight = 2.0;
    description = "From address is listed in Barracuda Reputation Block List (BRBL)";
    groups = ["barracuda"];
  }
  "RECEIVED_BARRACUDA" {
    weight = 1.0;
    description = "Received address is listed in Barracuda Reputation Block List (BRBL)";
    groups = ["barracuda"];
    one_shot = true;
  }

  "RBL_FABEL" {
    weight = 2.0;
    description = "From address is listed in Fabel Spamsources";
    groups = ["fabel"];
  }
  "RECEIVED_FABEL" {
    weight = 1.0;
    description = "Received address is listed in Fabel Spamsources";
    groups = ["fabel"];
    one_shot = true;
  }

  "RBL_DRONEBL" {
    weight = 2.0;
    description = "From address is listed in DroneBL";
    groups = ["dronebl"];
  }
  "RECEIVED_DRONEBL" {
    weight = 1.0;
    description = "Received address is listed in DroneBL";
    groups = ["dronebl"];
    one_shot = true;
  }

  "RBL_EFNET" {
    weight = 2.0;
    description = "From address is listed in EFnet RBL";
    groups = ["efnet"];
  }
  "RECEIVED_EFNET" {
    weight = 1.0;
    description = "Received address is listed in EFnet RBL";
    groups = ["efnet"];
    one_shot = true;
  }
}
