symbols {
  "RBL_SPAMCOP" {
    weight = 2.0;
    description = "From address is listed in SpamCop Blocking List (SCBL)";
    groups = ["spamcop"];
  }
  "RECEIVED_SPAMCOP" {
    weight = 1.0;
    description = "Received address is listed in SpamCop Blocking List (SCBL)";
    groups = ["spamcop"];
  }

  "RBL_BARRACUDA" {
    weight = 2.0;
    description = "From address is listed in Barracuda Reputation Block List (BRBL)";
    groups = ["barracuda"];
  }
  "RECEIVED_BARRACUDA" {
    weight = 1.0;
    description = "Received address is listed in Barracuda Reputation Block List (BRBL)";
    groups = ["barracuda"];
  }

  "RBL_FABEL" {
    weight = 2.0;
    description = "From address is listed in Fabel Spamsources";
    groups = ["fabel"];
  }
  "RECEIVED_FABEL" {
    weight = 1.0;
    description = "Received address is listed in Fabel Spamsources";
    groups = ["fabel"];
  }
}
