authenticated {
  priority = high;
  authenticated = yes;
  apply {
    groups_disabled = ["dmarc", "fuzzy", "rbl"];
    actions {
        "add header" = null;
    }
  }
}

local {
  priority = high;
  local = yes;
  apply {
    groups_disabled = ["dmarc", "fuzzy", "rbl"];
    actions {
        "add header" = null;
    }
  }
}

# only perform lookups based on email addresses or message content for specific senders
lookup_privacy {
  inverse = yes;
  from_mime = "@gmail.com";
  from_mime = "@hotmail.com";
  from_mime = "@outlook.com";
  apply {
    groups_disabled = ["fuzzy"];
    symbols_disabled = ["MSBL_EBL", "RSPAMD_EMAILBL", "ABUSIX_EMAILBL", "ABUSIX_BITCOIN"];
  }
}
