authenticated {
  priority = high;
  authenticated = yes;
  apply {
    groups_disabled = ["dmarc", "rbl"];
    actions {
        "add header" = null;
    }
  }
}

local {
  priority = high;
  local = yes;
  apply {
    groups_disabled = ["dmarc", "rbl"];
    actions {
        "add header" = null;
    }
  }
}
