authenticated {
  priority = high;
  authenticated = yes;
  apply {
    groups_disabled = ["dmarc", "rbl"];
    actions {
        "add header" = null;
    }
  }
}

local {
  priority = high;
  local = yes;
  apply {
    groups_disabled = ["dmarc", "rbl"];
    actions {
        "add header" = null;
    }
  }
}

# only look up email addresses in RBLs for specific senders
rbl_address_privacy {
  inverse = yes;
  from_mime = "@gmail.com";
  from_mime = "@hotmail.com";
  from_mime = "@outlook.com";
  apply {
    symbols_disabled = ["MSBL_EBL", "RSPAMD_EMAILBL"];
  }
}
