symbols {
  "RSPAMD_EMAILBL" {
    weight = 1.0;
  }

  "RSPAMD_URIBL" {
    weight = 1.0;
  }

  "ABUSIX_EMAILBL" {
    weight = 1.0;
    description = "An email address in the message is listed in Abusix Email Blocklist";
    one_shot = true;
    groups = ["abusix"];
  }

  "ABUSIX_DOMAIN" {
    weight = 1.0;
    description = "A domain in the message is listed in Abusix Domain Blocklist";
    one_shot = true;
    groups = ["abusix"];
  }

  "SEM_URIBL" {
    weight = 3.0;
  }

  "SEM_URIRED" {
    weight = 0.5;
    groups = ["sem"];
    one_shot = true;
  }

  "SEM_FRESH_1" {
    weight = 0.5;
    groups = ["sem"];
    one_shot = true;
  }

  "SEM_FRESH_5" {
    weight = 0.5;
    groups = ["sem"];
    one_shot = true;
  }

  "SEM_FRESH_10" {
    weight = 0.5;
    groups = ["sem"];
    one_shot = true;
  }

  "SEM_FRESH_15" {
    weight = 0.5;
    groups = ["sem"];
    one_shot = true;
  }

  "SEM_FRESH_30" {
    weight = 2.0;
    groups = ["sem"];
    one_shot = true;
  }

  "ABUSIX_BITCOIN" {
    weight = 2.0;
    description = "A Bitcoin address in the message is listed in Abusix Domain Blocklist";
    one_shot = true;
    groups = ["abusix"];
  }
}
