symbols {
  "ABUSIX_EMAILBL" {
    weight = 2.0;
    description = "An email address in the message is listed in Abusix Email Blocklist";
    one_shot = true;
    groups = ["abusix"];
  }

  "ABUSIX_DOMAIN" {
    weight = 7.5;
    description = "A domain in the message is listed in Abusix Domain Blocklist";
    one_shot = true;
    groups = ["abusix"];
  }

  "ABUSIX_BITCOIN" {
    weight = 2.0;
    description = "A Bitcoin address in the message is listed in Abusix Domain Blocklist";
    one_shot = true;
    groups = ["abusix"];
  }
}
