[Service]
CapabilityBoundingSet=
CapabilityBoundingSet=CAP_CHOWN CAP_DAC_OVERRIDE CAP_NET_BIND_SERVICE CAP_SETUID CAP_SETGID CAP_SYS_CHROOT
LockPersonality=yes
MemoryDenyWriteExecute=yes
NoNewPrivileges=yes
PrivateIPC=yes
ProcSubset=pid
ProtectClock=yes
ProtectControlGroups=yes
ProtectHome=yes
ProtectHostname=yes
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectProc=invisible
ProtectSystem=strict
ReadWritePaths=/var/lib/postfix /var/spool/postfix
Restart=always
RestartMaxDelaySec=10s
RestartSec=100ms
RestartSteps=5
RestrictAddressFamilies=AF_INET AF_INET6 AF_NETLINK AF_UNIX
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service chroot
SystemCallFilter=~@keyring

# set up chroot in /var/spool/postfix
TemporaryFileSystem=/var/spool/postfix/etc:ro
BindReadOnlyPaths=/etc/hosts:/var/spool/postfix/etc/hosts
BindReadOnlyPaths=/etc/resolv.conf:/var/spool/postfix/etc/resolv.conf
BindReadOnlyPaths=/etc/services:/var/spool/postfix/etc/services
BindReadOnlyPaths=/etc/ssl/certs/ca-certificates.crt:/var/spool/postfix/etc/ssl/certs/ca-certificates.crt
