whitelist_domains_url = [
  "$LOCAL_CONFDIR/local.d/maps.d/greylist-whitelist-domains.map",
  "$LOCAL_CONFDIR/local.d/maps.d/dmarc_upgrade.map",
];

whitelist_symbols = [
  "WHITELIST_SPF",
  "WHITELIST_DKIM",
  "WHITELIST_SPF_DKIM",
  "WHITELIST_DMARC",
  "GOOD_ADDR",
  "GOOD_ESLD",
];
