whitelist_domains_url = [
  "$LOCAL_CONFDIR/local.d/maps.d/greylist-whitelist-domains.map",
  "$LOCAL_CONFDIR/local.d/maps.d/dmarc_upgrade.map",
  "https://maps.rspamd.com/rspamd/dmarc_whitelist_new.inc",
];
