# work around lack of HTTPS with a manual local cache
attached_maps = [
  {
    selector_alias = "surbl_hashbl_map",
    description = "SURBL hashbl map",
    url = "regexp;$LOCAL_CONFDIR/local.d/maps.d/surbl-hashbl.map",
  }
]
